events { }

http {
    upstream search_engine_nodes {
  	server 10.26.14.237:4567;
	server 10.26.14.240:4567;
	server 10.26.14.234:4567;
	server 10.26.14.235:4567;
	server 10.26.14.231:4567;
	server 10.26.14.232:4567;
	server 10.26.14.233:4567;

	server 10.26.14.228:4567;
	server 10.26.14.229:4567;
	server 10.26.14.230:4567;
	server 10.26.14.225:4567;
	server 10.26.14.226:4567;
	server 10.26.14.227:4567;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://search_engine_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Backend-Server $hostname;
        }
    }
}